### ISSUE TITLE
Please restore original copyright license notice

### ISSUE THREAD

**Issue by asabil** [artemeff/raven-erlang#18]
This code was originally written by myself, and I would expect the original license file to remain intact: https://github.com/asabil/raven-erlang/blob/master/LICENSE

You are free to add additional copyright notices, but you can't remove the original.

**Comment by artemeff** [comment]
is it good now?

**Comment by asabil** [comment]
Could you please keep the original copyright line:

```
Copyright (c) 2012-2015 Ali Sabil
Copyright (c) 2018 Yuri Artemev
```

**Comment by artemeff** [comment]
done
