### ISSUE TITLE
add report handler in doc

### ISSUE THREAD

**Issue by stleon** [artemeff/raven-erlang#8]
Documentation says:
```
To start raven_erlang with your application, add in your myapp.app.src:

% ...
{applications, [
    % ...
    raven_erlang
]},
% ...
```

So, in applications section we have list of all applications that must be started **before** main application is started. And we have -- **raven_erlang** in that list.

Ok, lets look at [this](https://github.com/artemeff/raven-erlang/blob/master/src/raven_app.erl#L11):
```
case application:get_env(?APP, error_logger) of
            {ok, true} ->
                error_logger:add_report_handler(raven_error_logger);
            _ ->
                ok
        end
```
 Here we get env **error_logger** from [here](https://github.com/artemeff/raven-erlang/blob/master/src/raven_erlang.app.src#L8):

```
    , {env,
            [ {error_logger, false}
            , {ipfamily, inet}
            ]}
```

So, **raven-erlang** starts without adding report handler **raven_error_logger**, but I have in **sys.config**:
```
    {raven_erlang, [
                        {dsn, "http://lol"},
                        {error_logger, true},
                        {error_logger_config, [
                                         {level, warning},
                                         {filter, raven_filter}]
                        }
                   ]
    }
```
We need to do it manually:
```
error_logger:add_report_handler(raven_error_logger),
```

Is it a bug in doc or a feature?

Thanks!

**Comment by MonsieurV** [comment]
> So, raven-erlang starts without adding report handler raven_error_logger, but I have in sys.config

To my understanding, it does use the `raven_error` entry you have overridden in your `sys.config`.

At least I remember using it exactly this way in the 0.3.5 release:

```erlang
{raven_erlang, [
        {dsn, "https://XX@sentry.io/XX"},
        {error_logger, true}
    ]}
```

Do you use any logger framework that could change the error logger handlers?

**Comment by stleon** [comment]
> Do you use any logger framework that could change the error logger handlers?

Yes, I use lagger & sasl (for reports). I tested it on turned off sasl error logger:
```
{sasl, [{sasl_error_logger, false}
           ]},
```
raven_error_logger handler does not adding automatically.

The problem is in lager. I turn off error_logger_redirect:

```
lager, [
        {error_logger_redirect, false},
```
And now it works! Thanks!

**Comment by stleon** [comment]
my mistake, without sasl it works:
```
{sasl, [
     {sasl_error_logger, false}
]}
```
